environment: production
app:
  name: online-store
  replicaCount: 3
  image:
    name: vladoiliev02/online-store
    tag: "1.0.0"
    pullPolicy: Always
  port:
    name: app-port
    number: 8080
  resources:
    requests:
      cpu: 1
      memory: 512M
    limits:
      cpu: 2
      memory: 1024M
  probes:
    liveness: /api/v1/liveness
    readiness: /api/v1/readiness
  env:
    config:
      PORT: "30080"
      DB_DRIVER_NAME: "postgres"
    secrets:
      DB_CONNECTION_STRING: "host=localhost port=5342 user=postgres password=Test1234 dbname=online_store sslmode=disable"
      SESSION_STORE_KEY: "secretKey"
      CLIENT_ID: "18725992034-4ohlj8tha3rr6rmf7pb6tvh8fhf58fql.apps.googleusercontent.com"
      CLIENT_SECRET: "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"

