apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.app.config.name }}
data:
  {{- range $key, $value := .Values.app.env.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}