apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.app.name }}-deployment
  labels:
    {{- include "online-store.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      {{- include "online-store.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "online-store.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.gcp.sql.sa_name }}
      volumes:
      - name: {{ .Values.gcp.sql.secret }}
        secret:
          secretName: {{ .Values.gcp.sql.secret }}
          optional: false
      containers:
      - name: {{ .Values.app.name }}
        image: "{{ .Values.app.image.name }}:{{ .Values.app.image.tag }}"
        imagePullPolicy: {{ .Values.app.image.pullPolicy }}
        ports:
        - name: {{ .Values.app.port.name }}
          containerPort: {{ .Values.app.port.number }}
        envFrom:
        - configMapRef:
            name: {{ .Values.app.config.name }}
        - secretRef:
            name: {{ .Values.app.secret.name }}
        readinessProbe:
          httpGet:
            path: {{ .Values.app.probes.readiness }}
            port: {{ .Values.app.port.number }}
        livenessProbe:
          httpGet:
            path: {{ .Values.app.probes.liveness }}
            port: {{ .Values.app.port.number }}
        resources:
          {{- toYaml .Values.app.resources | nindent 10 }}
      - name: cloud-sql-proxy
        image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.8.0
        args:
          - "--structured-logs"
          - "--port={{ .Values.gcp.sql.port }}"
          - "--credentials-file=/secrets/{{ .Values.gcp.sql.file }}"
          - "{{ .Values.gcp.sql.connection_name }}"
        securityContext:
          runAsNonRoot: true
        resources:
          requests:
            memory: "512Mi"
            cpu: "0.5"
        volumeMounts:
          - name: {{ .Values.gcp.sql.secret }}
            mountPath: /secrets/
            readOnly: true