apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.gcp.ip_name }}-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.gcp.ip_name }}
    networking.gke.io/managed-certificates: {{ .Values.tls.managed_cert }}
    kubernetes.io/ingress.allow-http: "false"
spec:
  rules:
  - hosts:
    - {{ .Values.app.host }}
    http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Values.app.name }}-service
            port:
              number: {{ .Values.app.port.number }}