apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.app.secret.name }}
type: Opaque
data:
  {{- range $key, $value := .Values.app.env.secrets }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
