apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-service
  labels:
    {{- include "online-store.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "online-store.labels" . | nindent 4 }}
  ports:
    - port: {{ .Values.app.port.number }}
      name: {{ .Values.app.port.name }}
      targetPort: {{ .Values.app.port.name }}